driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: current

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:

- name: amazonlinux
  driver:
    image: amazonlinux:latest
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum -y install lsof which initscripts net-tools sudo wget

suites:
- name: default
  run_list:
  - recipe[yum-amazon::default]